js_get_elements = ("function getXPosition(el) {return el.getBoundingClientRect().left;}"
                "function getYPosition(el) {return el.getBoundingClientRect().top+window.scrollY;}"
                "function getMaxWidth(el) {return el.getBoundingClientRect().width;}"
                "function getMaxHeight(el) {return el.getBoundingClientRect().height;}"
                "function elementIsVisible(el) {if (getComputedStyle(el).visibility === 'hidden' || el.getBoundingClientRect().height == 0) return false; return true;}"
                "function getXPath(element) {const idx = (sib, name) => sib ? idx(sib.previousElementSibling, name||sib.localName) + (sib.localName == name): 1; const segs = elm => !elm || elm.nodeType !== 1 ? ['']: [...segs(elm.parentNode), elm instanceof HTMLElement? `${elm.localName}[${idx(elm)}]`: `*[local-name() = '${elm.localName}'][${idx(elm)}]`]; return segs(element).join('/');}"
                "function getIdXPath(element) {const idx = (sib, name) => sib ? idx(sib.previousElementSibling, name||sib.localName) + (sib.localName == name): 1; const segs = elm => !elm || elm.nodeType !== 1 ? ['']: elm.id && document.getElementById(elm.id) === elm ? [`//*[@id='${elm.id}']`]: [...segs(elm.parentNode), elm instanceof HTMLElement? `${elm.localName}[${idx(elm)}]`: `*[local-name() = '${elm.localName}'][${idx(elm)}]`]; return segs(element).join('/');}"
                "var result = []; " 
			    "var all = document.querySelectorAll('input,textarea,button,select,a,h1,h2,h3,h4,h5,h6,li,span,div,p,th,tr,td,label,svg'); "
				"for (var i=0, max=all.length; i < max; i++) { "
				"    if (elementIsVisible(all[i])) result.push({'tag': all[i].tagName, 'class': all[i].className, 'type': all[i].type, 'name': all[i].name, 'id': all[i].id, 'value': all[i].value, 'href': all[i].href, 'placeholder': all[i].placeholder, 'title': all[i].title, 'alt': all[i].alt, 'x': getXPosition(all[i]), 'y': getYPosition(all[i]), 'width': getMaxWidth(all[i]), 'height': getMaxHeight(all[i]), 'children': all[i].children.length, 'xpath': getXPath(all[i]), 'idxpath': getIdXPath(all[i])}); "
				"} "
                " return JSON.stringify(result); ")

js_get_element = ("function getXPosition(el) {return el.getBoundingClientRect().left;}"
                "function getYPosition(el) {return el.getBoundingClientRect().top+window.scrollY;}"
                "function getMaxWidth(el) {return el.getBoundingClientRect().width;}"
                "function getMaxHeight(el) {return el.getBoundingClientRect().height;}"
                "function elementIsVisible(el) {if (getComputedStyle(el).visibility === 'hidden' || el.getBoundingClientRect().height == 0) return false; return true;}"
                "function getXPath(element) {const idx = (sib, name) => sib ? idx(sib.previousElementSibling, name||sib.localName) + (sib.localName == name): 1; const segs = elm => !elm || elm.nodeType !== 1 ? ['']: [...segs(elm.parentNode), elm instanceof HTMLElement? `${elm.localName}[${idx(elm)}]`: `*[local-name() = '${elm.localName}'][${idx(elm)}]`]; return segs(element).join('/');}"
                "function getIdXPath(element) {const idx = (sib, name) => sib ? idx(sib.previousElementSibling, name||sib.localName) + (sib.localName == name): 1; const segs = elm => !elm || elm.nodeType !== 1 ? ['']: elm.id && document.getElementById(elm.id) === elm ? [`//*[@id='${elm.id}']`]: [...segs(elm.parentNode), elm instanceof HTMLElement? `${elm.localName}[${idx(elm)}]`: `*[local-name() = '${elm.localName}'][${idx(elm)}]`]; return segs(element).join('/');}"
                "var result = []; "
			    "var elem = arguments[0]; "
				"result.push({'tag': elem.tagName, 'class': elem.className, 'type': elem.type, 'name': elem.name, 'id': elem.id, 'value': elem.value, 'href': elem.href, 'placeholder': elem.placeholder, 'title': elem.title, 'alt': elem.alt, 'x': getXPosition(elem), 'y': getYPosition(elem), 'width': getMaxWidth(elem), 'height': getMaxHeight(elem), 'children': elem.children.length, 'xpath': getXPath(elem), 'idxpath': getIdXPath(elem)}); "
                "return JSON.stringify(result); ")